### ISSUE TITLE
att-induction for multi-label case

### ISSUE THREAD

**Issue by hquzhuguofeng** [ShaneTian/Att-Induction#3]
感谢作者对于induction network的改进和无私的分享。我已经学习过您的相关代码。induction network相比于多标签分类，应该是比较适合多分类的。这是我的理解：
1、在计算label向量的表示的过程中，如果一个样本只有一个label的话，那么通过动态路由的算法，得到的label的向量的表示是相对比较清晰的。但是如果样本中有多个label的话，label语义的耦合会严重点。
2、在整理训练集和验证集的过程中，训练集的标签和验证集的标签如果是多标签的分类的话，好像比较难处理。
我的问题是：
1、induction network是否适合多标签的分类，可能我对动态路由的算法还不是理解的十分到位（感觉好像又适合，哈哈）
2、假如适合的话，在构建训练集和验证集的过程中，我应该如何分配label？
3、假如不适合，是否有比较好的处理方法？
实验我自己也会去做的，将代码改成多标签分类，同时也希望和作者您交流下这个问题，期待您的回复。

**Comment by ShaneTian** [comment]
感谢关注该工作。
你的理解是正确的。
1. Induction Network 及 Att-Induction Network 都不适合做多标签分类。
    1. Dynamic Routing 本来就是起到了 induction 的作用，如果多标签的话，实际上归纳后的向量是表意不明的；
    2. Attention 使得对于不同的 query 可以得到不同的类别归纳向量，没有想到与多标签有什么关系。
2. 建议关注一些专门做小样本多标签分类的文章或者多标签分类的文章是否可以进行小样本学习等。如 https://arxiv.org/pdf/2010.05256.pdf 与它的相关工作。
