### ISSUE TITLE
question about script execution

### ISSUE THREAD

**Issue by zhang86265** [ShaneTian/Att-Induction#5]
您好，麻烦问下我执行了run_train_ARSC.sh，但是log下并没有新的日志和结果产生，是因为data_set还是test_data没有传进去导致吗？test_data指定的文件我是不是应该放到和run_train_ARSC.sh脚本同一层目录下，求解答

**Comment by ShaneTian** [comment]
新建 `data/ARSC/` 目录，将数据放在里面。
 https://github.com/ShaneTian/Att-Induction/blob/9ae11ee30485181b9014b15ac927eb8b2a4170be/src/train.py#L233
